# NLP란?


In [26]:
list1 = [ 20,10,5]   #객체
#print(list1)    #함수이름( 입력값)
#list2라는 자료구조, "홍길동", "임꺽정" print 출력
list2 = ["홍길동", "임꺽정", "장길산"]
#print(list2)

list2[ 0 ] #특정 순서의 값을 선택, 인덱싱
list2[0:2] #슬라이싱, 특정 범위의 값을 선택

list1 * 3

[20, 10, 5, 20, 10, 5, 20, 10, 5]

In [31]:
import numpy as np
a1 = np.array(list1)    #array자료구조를 만드는 numpy의 array함수
a1 * 3


array([60, 30, 15])

In [37]:
list3 = [  list1, list1     ]
list3
a2 = np.array( list3 )
pd.DataFrame( a2 )

0   1  2
0  20  10  5
1  20  10  5

In [ ]:
import pandas as pd
df1 = pd.read_csv("news.csv")
df1  #pandas의 2차원 자료구조, 데이터프레임, DataFrame
#df1.info()
df1[ "articles"  ]  #특정 컬럼 선택

# data_sent_new.csv를 읽으셔서, sentence라는 컬럼을 선택해보세요
# 1. 파일업로드 2, pd.read_csv.... 3.컬럼선택
df2 = pd.read_csv("data_sent_new.csv", encoding = "cp949")
df2["sentence"]
df2.sentence    #위와 같은 결과

In [ ]:
!pip install konlpy

# mlxtend 설치해보세요
!pip install mlxtend

In [68]:
from konlpy.tag import Okt, Kkma
okt = Okt()   #형태소 분석기, Okt 형태소 분석기를 만드는 함수
okt.morphs("한글로 아무거나 입력하세요")   #nouns,   morphs(형태소분석함수)
okt.nouns("한글로 아무거나 입력하세요")   #nouns,   morphs(형태소분석함수

['한글', '거나', '입력']

In [69]:
kkma = Kkma()
kkma.morphs("한글로 아무거나 입력하세요")
kkma.nouns("한글로 아무거나 입력하세요")

['한글', '거', '입력']

In [56]:
df2.sentence[0]   #첫번째 글만 선택해서 출력
#첫번째 글->명사->result1, 두번째 글->명사->result2
result1 = okt.nouns( df2.sentence[0] )

In [ ]:
from konlpy.tag import Kkma
total = []
total.append( okt.nouns( df2.sentence[0] ) )  #첫번째 글->형태소분석->리스트에 추가

In [73]:
for i in df2.sentence[0:10] :
  total.append(okt.nouns(i) )
#전체 글들을 각각 형태소분석->리스트에 추가

# Open Korean Text: Okt
# Kkma
# train_df.csv 를 읽으세요-> 발화문 컬럼을 선택-> 1~100개의 글들에 대해서
# Kkma로 명사만 뽑아서 total2라는 리스트에 추가해주세요
df3 = pd.read_csv("train_df.csv", encoding="cp949")
total2 = []
kkma = Kkma()
for i in df3.발화문[0:100]:
  total2.append(kkma.nouns(i))

In [ ]:
df3.인텐트.value_counts()
df3.query(" 발화자== 'c' ")  #발화자가 c인 것만 선택

#발화자가 s인 행들의 인텐트 값의 빈도를 구해보세요.
df4 = df3.query(  " 발화자== 's' " ).인텐트.value_counts()
df3.query( "인텐트=='교환|반품|환불_시간_요청'"	)

In [ ]:
total4 = []
for i in [1,2,3]:
  total4.append(i+3)

[ i+3  for i in [1,2,3] ]

[ kkma.nouns(i) for i in df3.발화문[0:4] ]

#df3 발화문의 10~14번째 글들에 대해서 okt로 형태소 분석한 결과를 리스트로.....
[ okt.morphs(i) for i in df3.발화문[10:14] ]


In [ ]:
df3.발화문[10:14].replace("[0-9]", "", regex=True)
df3.발화문[10:14].replace("[A-Z]", "", regex=True)
df3.발화문[10:14].replace("[^ㄱ-ㅎㅏ-ㅣ가-힣]", "", regex=True)   #한글만 남기고 지우기(치환)



#1. NLP를 위한 Python 기초: 자료구조, 기본 문법

-기본 자료구조: List, Tuple, Set, Dictionary

In [1]:
list1 = [ 20,10,5]  #리스트
#실행: 플레이버튼, 또는  ctrl+enter
print( list1 )
list1[ 1 ]#인덱싱
list1[ 1:3 ] #슬라이싱
list1[ 2 ] = 40
list1[ 0 ] = "data"
list1.append( 1000000000 )
list1.append( list1 )

[20, 10, 5]


In [ ]:
tuple1 = ( 10,20,5 )
tuple1[1] = 40  #tuple의 값은은 수정 불가

TypeError: ignored

In [ ]:
set1 = { 10,20, 5}
#set1[ 1 ]#인덱싱 불가
dict1 = {  'a':10,  'b':20,  'c':5}
dict1 #key-value
dict1['a']

10

In [ ]:
list3 = [ 3, 2.1, "A", 10]
list3[ 1:3 ]
list3[  2 ] = 100
list3.append( 99 )
list3

[3, 2.1, 100, 10, 99]

In [ ]:
list4 = [1,2,3]
list5 = [ [1,2], [3,4]    ]
list5

[[1, 2], [3, 4]]

In [ ]:
dict2 = {'A':[1,2,3]  , 'B':[4,5,6] }
dict2

{'A': [1, 2, 3], 'B': [4, 5, 6]}

In [ ]:
list6 = []
list6.append( dict2 )
list6

[{'A': [1, 2, 3], 'B': [4, 5, 6]}]

-조건문과 반복문문

In [ ]:
a = 75
if a > 70 :
  print("탕수육")

탕수육


In [ ]:
c=91
d=50
if (c > 90) | (d > 90):
  print("pizza")

pizza


In [ ]:
# sales3 = [ 10, 11, 8, 9, 12]
# sales3의 값 중에서 10보다 작은 숫자들만 선택을해서,
# 5를 더해서 리스트로 만드세요
sales3 = [ 10, 11, 8, 9, 12]
[ i+5 for i in sales3 if i < 10  ]
#위와 같은 작업을 하는 ....
result = []
for i in sales3:
  if i < 10:
    result.append(i+5)

- Numpy array생성 및 차원 확인

In [ ]:
import numpy as np
a = np.array( [0,1,2,3,4, 5.0])
a.shape #차원, 값의 개수
a.ndim
a.dtype #값의 종류, array->단일한 type의 값, 정수와 실수->실수

dtype('float64')

In [ ]:
a.reshape( (3,2)  ) #a가 변경되지는 않음

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

- array 연산과 인덱싱

In [ ]:
b = a.reshape( (3,2)  ) #a가 변경되지는 않음
b[  1  , 1     ]
b[ [0,2], 1]
b[ 0:2, 0]
b[ : , 0]  #1열만
b[  1 ,  :  ] #2행만

array([2., 3.])

In [ ]:
a > 3
a[  [False, False, False, False,  True,  True] ]
a[   a>3   ] #3보다 큰 값만 출력

array([4., 5.])

- NaN 값의 처리

In [ ]:
import numpy as np
np.array( [ 1,2,np.NAN,4])
np.NAN # not a number

nan

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
np.isnan(c)
c[ ~np.isnan(c) ]

np.mean( c[~np.isnan(c) ])

2.5

- Pandas DataFrame

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series( [1,2,3], index=["r1","r2","r3"]   )
s1.index
s1.values
s2 = pd.Series( [1,2,3], index=["r3","r2","r1"]   )
s1+s2

df1=pd.DataFrame([[1,2],[3,4]],index=["r1","r2"],columns=["c1","c2"] )
df1.index # df1.columns #df1.values
#df1.info()
df1.describe()
df2=pd.DataFrame([[1,2], [3,4]],index=["r3","r2"],columns=["c3","c2"])
df1+df2
df1.columns=["c3", "c2"]


#2. 텍스트 읽고 처리하기

- CSV 읽기기

In [ ]:
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_train.txt
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_test.txt

--2023-03-28 21:58:48--  https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt [following]
--2023-03-28 21:58:48--  https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14628807 (14M) [text/plain]
Saving to: ‘ratings_train.txt’

ratings_train.txt   100%[===================>]  13.95M  --.-KB/s    in 0.05s   



In [ ]:
import pandas as pd

train_df = pd.read_csv('ratings_train.txt', sep='\t')
train_df.head(3)
train_df['label'].value_counts( )

0    75173
1    74827
Name: label, dtype: int64

- 폴더 내 여러 파일 읽기

In [ ]:
!unzip news_small.zip

In [ ]:
import os
import pandas as pd

files1 = os.listdir('103')   #압축이 풀린 103폴더의 파일들을 읽음
files2 = os.listdir('105')   #압축이 풀린 105폴더의 파일들을 읽음

In [ ]:
y = []
x = []

#txt파일을 읽어서 파일 내용을 x라는 리스트에 추가
def add_file(path):
    with open(path, "r", encoding="utf-8") as f:
        s = f.read()
        x.append(s)

In [ ]:
#반복문, 똑같은 작업을 여러 대상에 적용
for f in files1:  #파일갯수만큼 반복
     add_file("103/"+f) #103폴더 신문기사가 X에 추가
     y.append(0)#103폴더 신문기사만큼 y에 0값을 추가, 0은 103을 나타내는 범주

for f in files2:
     add_file("105/"+f)
     y.append(1)  #105를 나타내는 범주 1

In [ ]:
len(y)

400

In [ ]:
x[0]

'정무비서관 보좌… 박정희 대통령 온통 경제개발만 생각, 말석 사람 챙기고 야근자에 밤참 보내박정희 대통령(오른쪽)이 1970년 청와대에서 열린 수출확대회의를 마치고 재무부 이재1과장이던 이용만 장로를 격려하고 있다.1966년 7월부터 청와대 비서실에서 일했다. 당시 청와대 비서실 조직은 비서실장 밑에 정무비서관이 있고 그 밑에 비서관(지금의 수석비서관)들이 소속된 체계였다. 오늘날엔 정무비서관이 국회와 정당 관계만 조율하지만, 그땐 모든 비서관을 통제하는 국정 총괄 기능을 맡았다. 재무부 차관을 지내고 막 청와대에 발탁된 서봉균 정무비서관을 보좌하는 게 내 역할이었다. 나는 청와대에서 열리는 대통령 주재 회의의 안건, 참석자 선정과 연락, 회의 후 속기록 작성 등을 맡았다. 가장 중요한 일은 회의 결과를 대통령 지시 각서 형태로 정리해 정무비서관과 비서실장을 거쳐 대통령의 결재를 받은 다음 각 부서에 전달하는 업무였다. 박정희 대통령이 일하는 모습을 가까운 거리에서 지켜봤다. 박 대통령은 ‘기획 및 계획, 집행, 평가와 분석’ 이라는 공식에 입각해 일했다. 체계적·과학적·능률적 프로젝트 수행을 강조했다. 나는 대통령 집무실 바로 옆에 있는 상황실에서 높이 5m, 길이 8m 되는 직사각형 상황판을 통해 부처별 주요 프로젝트의 완공 계획, 진행 실적, 문제점을 일목요연하게 표시하고 관리하는 일을 했다. 수출입 동향, 세수 현황, 산업시설 건설 현황 등을 담은 통계와 도표뿐 아니라 완공된 공장, 건설 중인 공정, 건설 계획 중인 공장을 표시하는 굴뚝 그림으로 지도 곳곳이 가득 찼다. 나는 대통령이 상황실에 들어올 기미가 있으면 언제든 답할 준비를 하면서 대기했다. 덕분에 리더의 입장에서 문제를 바라봤고 경제개발계획을 한눈에 익힐 수 있었다. 박 대통령은 상황실에 들어와 빨간 줄이 길게 늘어나지 않은 프로젝트에 대해 “왜 이렇게 더디게 진행되고 있나”라고 물었다. 그러면 나는 주저 없이 “네, 이 프로젝트는 이런저런 이유로 지체되고 있습니다”라고 답할 수 있어야 했

In [ ]:
df = pd.DataFrame( {'label':y, 'articles':x })
df.to_csv("news.csv")

#3. 패키지 설치 및 형태소 분석

- KoNLPy 제공 형태소 분석기 활용
 - Hannanum: 한나눔. KAIST Semantic Web Research Center 개발.
 - Kkma: 꼬꼬마. 서울대학교 IDS(Intelligent Data Systems) 연구실 개발.
 - Komoran: 코모란. Shineware에서 개발.
 - Mecab: 메카브. 일본어용 형태소 분석기를 한국어를 사용할 수 있도록 수정.
 - Open Korean Text: 오픈 소스 한국어 분석기. 과거 트위터 형태소 분석기.

In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from konlpy.tag import Okt #Okt라는 함수만 부르기기
okt=Okt()  #형태소 분석 객체가 만들어짐

In [ ]:
okt.nouns("반찬들은 다양해서 맘에 드는데")

['반찬', '맘']

In [ ]:
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
# 텍스트를 형태로 단위로 나누는데,이때 각 단어에서 어간을 추출

print(okt.pos('열심히 코딩한 당신, 연휴에는 여행을 가봐요'))
# 품사추출.

print(okt.nouns('열심히 코딩한 당신, 연휴에는 여행을 가봐요'))
# 명사추출.


['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
[('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
['코딩', '당신', '연휴', '여행']


In [ ]:
from konlpy.tag import Kkma
kkma=Kkma()
print(kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print(kkma.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print(kkma.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
[('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]
['코딩', '당신', '연휴', '여행']


- 예제 데이터 다운로드

In [ ]:
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_train.txt
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_test.txt

import pandas as pd
train_df = pd.read_csv('ratings_train.txt', sep='\t')

--2023-03-28 22:02:06--  https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt [following]
--2023-03-28 22:02:06--  https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14628807 (14M) [text/plain]
Saving to: ‘ratings_train.txt’

ratings_train.txt   100%[===================>]  13.95M  --.-KB/s    in 0.1s    



In [102]:
def func1(text):
   result = okt.nouns( text )
   return result

func1("5분 있으면 쉬는 시간" )


['시간']

In [103]:
from konlpy.tag import Okt
Okt = Okt()

def tokenizer(text):
    # 입력 인자로 들어온 text 를 형태소 단어로 토큰화 하여 list 객체 반환
    tokens_ko = Okt.morphs(text)
    return tokens_ko

#4. DTM 만들기

- 형태소 분석 후 Document Term Matrix 구성

In [104]:
import pandas as pd
df = pd.read_csv("news.csv")
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split( df, test_size=0.3)

In [117]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer #TF, DTM

# Okt 객체의 morphs( ) 객체를 이용한 tokenizer 사용
tf_vect = CountVectorizer(tokenizer=tokenizer)
dtm = tf_vect.fit_transform( train_df['articles'][0:10] )


/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# csv를 읽기
news = pd.read_csv("news.csv")
#news1 = news.query( "label==1")
# tokenizer 함수를 만들기
def func2(text):
   result = okt.nouns( text )
   return result
#스탑워즈: 불용어
words = ['기술', '제품', '서비스', '이용자', '사용자', '정보', '소비자', '시장', '업체', '인터넷']
# CountVectorizer로 DTM 만드는 객체 생성(tokenizer 지정)
vect = TfidfVectorizer(tokenizer=func2, stop_words=words, min_df=3)  #TfidfVectorizer
# dtm 생성 (객체.fit_transform(데이터프레임의 텍스트컬럼))
news.articles.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣]", "", regex=True, inplace=True  )
dtm_news = vect.fit_transform(  news.articles )

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
vect.get_feature_names_out()

vect.get_stop_words()
vect.vocabulary_

In [133]:
dic1 = { 1:'abc', 2:'def'    }
dic1[1]

'abc'


- Tfidf로 DTM 만들기

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
tfidf_vect = TfidfVectorizer(tokenizer=tokenizer, min_df=10)
tfidf_vect.fit(train_df['articles'])  #train의 명사를 뽑은 것까지

TfidfVectorizer(min_df=10, tokenizer=<function tokenizer at 0x7feef21b4940>)

In [ ]:
tfidf_matrix_train = tfidf_vect.transform(train_df['articles'])
tfidf_matrix_test = tfidf_vect.transform(test_df['articles'])

In [ ]:
tfidf_matrix_train

<280x1890 sparse matrix of type '<class 'numpy.float64'>'
	with 62404 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf_matrix_train.todense()

matrix([[0.00515071, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.0143323 , 0.        , 0.        , ..., 0.        , 0.02287888,
         0.02287888],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.02409341, 0.        ,
         0.        ],
        [0.03412783, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

In [ ]:
#시간 소요

def token(text):
    # 입력 인자로 들어온 text 를 형태소 단어로 토큰화 하여 list 객체 반환
    tokens_ko = Okt.nouns(text)
    return tokens_ko

from sklearn.feature_extraction.text import CountVectorizer
tf_vect = CountVectorizer(tokenizer=token, min_df=10)
tf_vect.fit_transform( df['articles'])

/usr/local/lib/python3.9/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<400x1730 sparse matrix of type '<class 'numpy.int64'>'
	with 54834 stored elements in Compressed Sparse Row format>

- 리스트로 형태소 구성

In [ ]:
!pip install tqdm #진행상태를 알려주는 기능 제공
!pip install konlpy

import tqdm
#값을 저장할 비어있는 리스트를 만듬.
tokenized_data = []

# 불용어 정의
stopwords = ['을', 'ㅋㅋ',
             '부터', '까지' '적', '의','가','이','은',
             '들','는','좀','잘','걍','과','도','를','으로',
             '자','에','와','한','하다', '점', '나']



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# 형태소 분석기 OKT를 사용한 토큰화 작업
from konlpy.tag import Okt
okt = Okt()

In [ ]:
texts = df["articles"].values.tolist()

for sentence in texts: #리뷰 각각에 대해서 아래작업 반복
    tokenized_sentence = okt.nouns(sentence)  #각 리뷰에서 명사만 뽑아서 리스트
    #위에서 명사만 추출한 결과에서, 각 명사가 stopwords인지 체크하고
    #stopwords 아닌 명사만 사용함
    stopwords_removed_sentence = [word for word in tokenized_sentence if not word in stopwords] # 불용어 제거
    tokenized_data.append(stopwords_removed_sentence)

len(tokenized_data)

400

In [ ]:
!pip install konlpy

In [13]:
import pandas as pd
news = pd.read_csv("news.csv")
news.articles.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣]", " ", regex=True, inplace=True  )
from konlpy.tag import Okt
okt = Okt()

In [15]:
result = []
stopwords =  ['을', '부터']
for i in news.articles[0:10]:
  tmp = okt.nouns( i )
  tmp2 = [   i      for i in tmp if not i in stopwords  ]
  result.append( tmp2 )

In [25]:
#data_sent_new.csv 파일->1~100행으로 제한->한글만 남기시고->
sent = pd.read_csv("data_sent_new.csv", encoding="cp949")
sent1 = sent[0:100]
sent1.sentence.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣]", " ", regex=True, inplace=True  )
#1) CountVectorizer로 dtm
def func1(text):
  result = okt.nouns( text )
  return result
stops = ['사람', '생활', '시간', '사회', '문제', '이야기', '경우', '상황', '이용', '대상']
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(tokenizer=func1, stop_words=stops)
dtm = vect.fit_transform( sent1.sentence )
#2) list의 list형태로 표현
result = []
for i in sent1.sentence:
  tmp = okt.nouns(i)
  tmp2 = [i for i in tmp if not i in stops]
  result.append( tmp2 )


<ipython-input-25-632b577c103e>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sent1.sentence.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣]", " ", regex=True, inplace=True  )
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
